export const IMAGE_HOME_DATA = 'IMAGE_HOME_DATA'
export const IMAGE_INS_DATA = 'IMAGE_INS_DATA'
export const IMAGE_BHXH_DATA = 'IMAGE_BHXH_DATA'

export const IMAGE_BHTN_DATA = 'IMAGE_BHTN_DATA'
export const IMAGE_BHYT_DATA = 'IMAGE_BHYT_DATA'
export const IMAGE_JOIN_DETAIL_DATA = 'IMAGE_JOIN_DETAIL_DATA'
export const HOMEDATA = 'HOMEDATA'
export const FIRST_TIME = 'FIRST_TIME'
export const TOKEN = 'TOKEN'
// 注册方式
export const REGISTERTYPE = 'REGISTERTYPE'
// 创建账号
export const CREATEACCOUNT = 'CREATEACCOUNT'
//创建密码
export const CREATEAPWD = 'CREATEAPWD'
//创建个人信息
export const SAVEPERSONINFO = 'SAVEPERSONINFO'
//保存选择区域
export const SAVEAREA = 'SAVEAREA'
//保存已有卡信息
export const SAVEACARDINFO = 'SAVEACARDINFO'
// 选择卡
export const SELECTCARDINFO = 'SELECTCARDINFO'
// modalize选择
export const SELECTMODALITEM = 'SELECTMODALITEM'
export const CLEEARMODALITEM = 'CLEEARMODALITEM'
// wallet 从哪个界面进入
export const WALLETADDMONEYFROM = 'WALLETADDMONEYFROM'

// 获取quickInfo
export const GETQUICKORDERINFO = 'GETQUICKORDERINFO'
// 从哪个模块进入
export const ORDERDETAILMODE = 'ORDERDETAILMODE'
// 进入orderdetail
export const TOORDERTAILMODENORMAL = 'TOORDERTAILMODENORMAL'
export const TOORDERTAILMODEQUICKORDER = 'TOORDERTAILMODEQUICKORDER'
// 购买卡
export const BUYNEWCARD = 'BUYNEWCARD'

export const REGISTER_GET_CARD_TYPE = 'REGISTER_GET_CARD_TYPE'

export const HOME_LOADING = 'HOME_LOADING'

export const SAVESECTIONTOKEN = 'SAVESECTIONTOKEN'

export const IMAGE_JOIN_DATA = 'IMAGE_JOIN_DATA'
